name: 'Continuous Integration'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Pip Update
        run: python -m pip install --upgrade pip
      
      - name: Install Core dependencies
        run: pip install -r requirements.txt 
      
      - name: Install Test dependencies
        run: pip install -r requirements-test.txt 

      - name: run Model Unit Tests
        run: make model-test
      
      - name: run API Unit Tests
        run: make api-test